name: Build and Deploy with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies with Bun
        run: |
          bun install --frozen-lockfile
        continue-on-error: false

      - name: Build Project with Bun
        run: |
          bun run build || exit 1

      - name: Deploy to Plesk
        run: |
          echo "Deploying to Plesk..."
        continue-on-error: false
